"""create roles

Revision ID: 99d9e8ba1d28
Revises: 1744c4736c80
Create Date: 2023-05-04 01:42:16.026528

"""
from alembic import op
from src.enums import RoleEnum
from uuid import uuid4
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99d9e8ba1d28"
down_revision = "1744c4736c80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.add_column("users", sa.Column("role_id", sa.Uuid(), nullable=True))
    op.create_foreign_key("users_role", "users", "roles", ["role_id"], ["id"])
    roles = [
        {"id": uuid4(), "name": role.name, "description": role.value}
        for role in RoleEnum
    ]
    op.bulk_insert(roles_table, roles)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_role", "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
